# Generated by Django 3.1.3 on 2022-10-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_date', models.DateTimeField(auto_now=True)),
                ('all', models.CharField(max_length=8)),
                ('allpass', models.CharField(max_length=8)),
                ('allfile', models.CharField(max_length=8)),
                ('allbug', models.CharField(max_length=8)),
                ('uiall', models.CharField(max_length=8)),
                ('uipass', models.CharField(max_length=8)),
                ('uifile', models.CharField(max_length=8)),
                ('uibug', models.CharField(max_length=8)),
                ('apiall', models.CharField(max_length=8)),
                ('apipass', models.CharField(max_length=8)),
                ('apifile', models.CharField(max_length=8)),
                ('apibug', models.CharField(max_length=8)),
            ],
        ),
    ]
