# Generated by Django 3.1.3 on 2022-11-21 10:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testhome', '0002_auto_20221012_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementModule',
            fields=[
                ('id', models.CharField(help_text='元素id', max_length=8, primary_key=True, serialize=False)),
                ('num', models.CharField(help_text='编号', max_length=10)),
                ('name', models.CharField(help_text='元素名称', max_length=20)),
                ('module_id', models.CharField(help_text='所述模块id', max_length=8)),
                ('project_id', models.CharField(help_text='所属项目id', max_length=50)),
                ('by', models.CharField(help_text='定位方式', max_length=20)),
                ('expression', models.CharField(help_text='元素表达式', max_length=200)),
                ('element_description', models.CharField(help_text='元素描述', max_length=200)),
                ('update_user', models.CharField(help_text='更新人', max_length=8)),
                ('create_user', models.CharField(help_text='创建人', max_length=8)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, help_text='更新时间')),
                ('status', models.CharField(help_text='元素在用状态', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='PageModule',
            fields=[
                ('id', models.CharField(help_text='页面模块id', max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='页面模块名称', max_length=20)),
                ('parent_id', models.CharField(help_text='父模块id', max_length=8)),
                ('project_id', models.CharField(help_text='所属项目id', max_length=50)),
                ('update_user', models.CharField(help_text='更新人', max_length=8)),
                ('create_user', models.CharField(help_text='创建人', max_length=8)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, help_text='更新时间')),
            ],
        ),
    ]
