# Generated by Django 3.1.3 on 2022-11-22 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testhome', '0003_elementmodule_pagemodule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagemodule',
            name='create_user',
            field=models.CharField(help_text='创建人', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='pagemodule',
            name='project_id',
            field=models.CharField(help_text='所属项目id', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pagemodule',
            name='update_user',
            field=models.CharField(help_text='更新人', max_length=8, null=True),
        ),
    ]
