# Generated by Django 3.1.3 on 2022-11-22 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testhome', '0007_auto_20221122_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elementmodule',
            old_name='id',
            new_name='element_id',
        ),
        migrations.RenameField(
            model_name='pagemodule',
            old_name='id',
            new_name='page_id',
        ),
    ]
