# Generated by Django 3.1.3 on 2022-11-22 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testhome', '0010_auto_20221122_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elementmodule',
            name='element_id',
        ),
        migrations.RemoveField(
            model_name='pagemodule',
            name='page_id',
        ),
        migrations.AddField(
            model_name='elementmodule',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagemodule',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
