# Generated by Django 3.1.3 on 2022-11-22 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testhome', '0011_auto_20221122_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementmodule',
            name='create_user',
            field=models.CharField(help_text='创建人', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='elementmodule',
            name='element_description',
            field=models.CharField(help_text='元素描述', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='elementmodule',
            name='module_id',
            field=models.CharField(help_text='所属模块id', max_length=8),
        ),
        migrations.AlterField(
            model_name='elementmodule',
            name='project_id',
            field=models.CharField(help_text='所属项目id', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='elementmodule',
            name='update_user',
            field=models.CharField(help_text='更新人', max_length=8, null=True),
        ),
    ]
