# Generated by Django 3.1.3 on 2022-11-22 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testhome', '0012_auto_20221122_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementmodule',
            name='status',
            field=models.CharField(default=1, help_text='元素在用状态', max_length=8),
        ),
    ]
