# Generated by Django 3.1.3 on 2022-12-01 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testhome', '0014_remove_elementmodule_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementmodule',
            name='module_id',
            field=models.ForeignKey(help_text='所属模块id', on_delete=django.db.models.deletion.DO_NOTHING, to='testhome.pagemodule'),
        ),
    ]
