# Generated by Django 3.1.3 on 2022-12-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testhome', '0015_auto_20221201_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementmodule',
            name='module_id',
            field=models.CharField(help_text='所属模块id', max_length=8),
        ),
    ]
